mac implementation

diff --git a/scripts/network-os/linux b/scripts/network-os/linux
--- a/scripts/network-os/linux
+++ b/scripts/network-os/linux
@@ -6,7 +6,7 @@ network_initialize() {
     hash ip 2>/dev/null || { echo >&2 "ip is required but it's not installed, aborting."; exit 1; }
     
     if [ ! -f /etc/NetworkManager/NetworkManager.conf ]; then
-        echo "cannot find NetworkManager.conf, abording."; exit 1
+        echo "[error] cannot find NetworkManager.conf, abording."; exit 1
     fi
 
     # get the default interface name
@@ -43,12 +43,12 @@ network_add_root_ca() {
     fi
 
     if [ ! -f "/usr/local/share/ca-certificates/docker-stack-root-ca.crt" ];then
-        echo "---> adding the root certificate in your trusted root certificates"
+        echo " ---> adding the root certificate in your trusted root certificates"
         sudo cp $__root/data/ssl/rootCA.pem /usr/local/share/ca-certificates/docker-stack-root-ca.crt
         sudo update-ca-certificates --fresh
         
         echo "[warn] register the root certificate $__root/data/ssl/rootCA.pem in your browser"
-        read -rsp $'Press any key to continue...\n' -n1 key
+        read -rsp $' ---> press any key to continue...\n' -n1 key
     fi
 }
 
diff --git a/scripts/ssl/create-root-ca b/scripts/ssl/create-root-ca
--- a/scripts/ssl/create-root-ca
+++ b/scripts/ssl/create-root-ca
@@ -3,29 +3,38 @@
 __dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 __root="$(dirname $(dirname $__dir))"
 
-echo "[info] generate the root certificate"
+generate_root_certificate() {
+    echo "[info] generate the root certificate"
 
-# check requirements
-hash openssl 2>/dev/null || { echo >&2 "[eroor] openssl need to be installed, aborting."; exit 1; }
-[ -z "$ROOT_CA_PASSWORD" ] && { echo "[error] need to set the ROOT_CA_PASSWORD environment variable, abording"; exit 1; }
+    if [ -f "$__root/data/ssl/rootCA.pem" ];then
+        echo " ---> the root certificate already exist, skipping"
+        return
+    fi
 
-echo "---> create ssl dir"
-mkdir -p $__root/data/ssl
+    # check requirements
+    hash openssl 2>/dev/null || { echo >&2 "[eroor] openssl need to be installed, aborting."; exit 1; }
+    [ -z "$ROOT_CA_PASSWORD" ] && { echo "[error] need to set the ROOT_CA_PASSWORD environment variable, abording"; exit 1; }
 
-echo "---> create the root certificate key"
-openssl genrsa \
--des3 \
--passout pass:$ROOT_CA_PASSWORD \
--out $__root/data/ssl/rootCA.key 2048
+    echo " ---> create ssl dir"
+    mkdir -p $__root/data/ssl
 
-echo "---> create the root certificate"
-openssl req \
--x509 \
--new \
--nodes \
--key $__root/data/ssl/rootCA.key \
--passin pass:$ROOT_CA_PASSWORD \
--sha256 \
--days 3650 \
--subj "/C=FR/ST=Paris/L=Paris/O=Lagardere/OU=IT Department/CN=lagardere-active.com" \
--out $__root/data/ssl/rootCA.pem
+    echo " ---> create the root certificate key"
+    openssl genrsa \
+    -des3 \
+    -passout pass:$ROOT_CA_PASSWORD \
+    -out $__root/data/ssl/rootCA.key 2048 > /dev/null
+
+    echo " ---> create the root certificate"
+    openssl req \
+    -x509 \
+    -new \
+    -nodes \
+    -key $__root/data/ssl/rootCA.key \
+    -passin pass:$ROOT_CA_PASSWORD \
+    -sha256 \
+    -days 3650 \
+    -subj "/C=FR/ST=Paris/L=Paris/O=Lagardere/OU=IT Department/CN=lagardere-active.com" \
+    -out $__root/data/ssl/rootCA.pem > /dev/null
+}
+
+
