various fixes

diff --git a/scripts/network b/scripts/network
--- a/scripts/network
+++ b/scripts/network
@@ -1,12 +1,11 @@
 #!/bin/bash
 
-set -o pipefail
+set -oe pipefail
 
 export __dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 export __root="$(dirname $__dir)"
 export __cmd=$1
 
-# load network functions for a given operating system
 bootstrap() {
     case "$OSTYPE" in
         darwin*)    source "$__dir/network-os/osx" ;; 
@@ -17,6 +16,28 @@ bootstrap() {
     esac
 
     network_initialize
+}
+
+load_env_file() {
+    if [ -f "$__root/.env" ];then
+        source "$__root/.env"
+    else
+        source "$__root/.env.dist"
+    fi
+}
+
+dnsmasq_config() {
+    export DNSMASQ_DNS=$(network_local_dns)
+    export DNSMASQ_LOCAL_DOMAIN=${DNSMASQ_LOCAL_DOMAIN:-".dev"}
+    export DNSMASQ_LOCAL_IP=$(network_local_ip)
+
+    if [ "$DNSMASQ_DNS" == "127.0.0.1" ];then
+        echo "[warn] Local DNS is already in place, skipping"
+        return
+    fi
+    
+    # Do not generate the file if it already exist
+    echo -e "$(expand_variables $__root/dnsmasq.conf.tpl)" > $__root/dnsmasq.conf
 }
 
 usage() {
@@ -33,15 +54,43 @@ usage() {
     exit 2
 }
 
+_before_enable() {
+    network_before_enable
+    load_env_file
+    dnsmasq_config
+}
+
+_enable() {
+    if [ docker top traefik 2> /dev/null ]; then
+        echo >&2 "[error] Your Docker Stack is already running, abording"
+        exit 1
+    fi
+    network_enable
+}
+
+_disable() {
+    network_disable
+    rm -f "$__root/dnsmasq.conf"
+}
+
+_add_root_ca() {
+    network_add_root_ca
+}
+
 main() {
     bootstrap
     case $__cmd in
-        'before')       network_before_enable ;;
-        'enable')       network_enable ;;
-        'disable')      network_disable ;;
-        'install-ca')   network_add_root_ca ;;
+        'before')       _before_enable ;;
+        'enable')       _enable ;;
+        'disable')      _disable ;;
+        'install-ca')   _add_root_ca ;;
         *)              usage ;;
     esac
+}
+
+# Expand bash variables from a file
+expand_variables() {
+    eval "cat <<EOF"$'\n'"$(cat "$1")"$'\n'"EOF"
 }
 
 main $1
diff --git a/scripts/network-os/linux b/scripts/network-os/linux
--- a/scripts/network-os/linux
+++ b/scripts/network-os/linux
@@ -1,20 +1,28 @@
 #!/bin/bash
 
+set -oe pipefail
+
 network_initialize() {
-    hash nmcli 2>/dev/null || { echo >&2 "nmcli is required but it's not installed, aborting."; exit 1; }
-    
-    hash ip 2>/dev/null || { echo >&2 "ip is required but it's not installed, aborting."; exit 1; }
-    
-    if [ ! -f /etc/NetworkManager/NetworkManager.conf ]; then
-        echo "[error] cannot find NetworkManager.conf, abording."; exit 1
+
+    if ! [ -x "$(command -v nmcli)" ];then
+        echo >&2 "[error] The nmcli cli utility is required but it's not installed, aborting."
+        exit 1
     fi
 
-    # get the default interface name
-    # @todo fail if no default interface is available
-    NIC=$(ip -o -4 route show to default | awk '{print $5}')
-    
-    # get the default interface UUID 
-    UUID=$(nmcli -f UUID,DEVICE connection | grep $NIC | awk '{ print $1 }')
+    if ! [ -x "$(command -v ip)" ];then
+        echo >&2 "[error] The ip cli utility is required but it's not installed, aborting"
+        exit 1
+    fi
+
+    if ! [ -f /etc/NetworkManager/NetworkManager.conf ]; then
+        echo >&2 "[error] Cannot find NetworkManager.conf, abording."; exit 1
+    fi
+
+    INTERFACE_NAME=$(ip -o -4 route show to default | awk '{print $5}')
+    if ! [ -n "$INTERFACE_NAME" ];then
+        echo >&2 "[error] Unable to dertermine your default network interface. Are your connected to the Internet ?"
+        exit 1
+    fi
 }
 
 network_before_enable() {
@@ -22,13 +30,16 @@ network_before_enable() {
 }
 
 network_enable() {
-    nmcli connection modify $UUID ipv4.ignore-auto-dns yes
-    nmcli connection modify $UUID ipv4.dns 127.0.0.1
+    nmcli con mod $INTERFACE_NAME connection.autoconnect yes
+    nmcli con mod $INTERFACE_NAME ipv4.ignore-auto-dns yes
+    nmcli con mod $INTERFACE_NAME ipv4.dns 127.0.0.1
     _restart_interface
 }
 
 network_disable() {
-    nmcli -f ipv4 connection modify $UUID ipv4.ignore-auto-dns no
+    nmcli con mod $INTERFACE_NAME connection.autoconnect yes
+    nmcli con mod $INTERFACE_NAME ipv4.ignore-auto-dns no
+    nmcli con mod $INTERFACE_NAME ipv4.dns ""
     _enable_system_dnsmasq
 }
 
@@ -36,13 +47,18 @@ network_local_ip() {
     ip route get 8.8.8.8 | head -1 | cut -d' ' -f8
 }
 
+network_local_dns() {
+    sleep 5
+    nslookup localhost | head -n1 | awk '{ print $2 }'
+}
+
 network_add_root_ca() {
-    if [ ! -f "$__root/data/ssl/rootCA.pem" ];then
-        echo "[error] generate a root certificate first, abording"
+    if ! [ -f "$__root/data/ssl/rootCA.pem" ];then
+        echo >&2 "[error] generate a root certificate first, abording"
         exit 1
     fi
 
-    if [ ! -f "/usr/local/share/ca-certificates/docker-stack-root-ca.crt" ];then
+    if ! [ -f "/usr/local/share/ca-certificates/docker-stack-root-ca.crt" ];then
         echo " ---> adding the root certificate in your trusted root certificates"
         sudo cp $__root/data/ssl/rootCA.pem /usr/local/share/ca-certificates/docker-stack-root-ca.crt
         sudo update-ca-certificates --fresh
@@ -64,6 +80,6 @@ _disable_system_dnsmasq() {
 }
 
 _restart_interface() {
-    nmcli device disconnect $NIC
-    nmcli device connect $NIC
+    nmcli device disconnect $INTERFACE_NAME
+    nmcli device connect $INTERFACE_NAME
 }
diff --git a/scripts/network-os/windows b/scripts/network-os/windows
--- a/scripts/network-os/windows
+++ b/scripts/network-os/windows
@@ -1,30 +1,39 @@
 #!/bin/bash
 
 network_initialize() {
-    _not_implemented
+    _not_implemented_warn
 }
 
 network_before_enable() {
-    _not_implemented
+    _not_implemented_warn
 }
 
 network_enable() {
-    _not_implemented
+    _not_implemented_warn
 }
 
 network_disable() {
-    _not_implemented
+    _not_implemented_warn
 }
 
 network_local_ip() {
-    _not_implemented
+    _not_implemented_error
+}
+
+network_local_dns() {
+    nslookup localhost | head -n1 | awk '{ print $2 }'
 }
 
 network_add_root_ca() {
-    _not_implemented
+    _not_implemented_warn
 }
 
-_not_implemented() {
+_not_implemented_warn() {
     echo "[warn] \"$__cmd\" is not yet implemented on windows"
     echo " ---> please read the windows documentation provided with this project"
+}
+
+_not_implemented_error() {
+    echo >&2 "[error] \"$__cmd\" is not yet implemented on windows"
+    echo >&2 " ---> please read the windows documentation provided with this project"
 }
